// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Instance information retrieved
 */
export const zGetInstanceResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instance information retrieved'),
    data: z.object({
        name: z.string(),
        version: z.string(),
        search_access: z.enum(['authenticated', 'public']),
        authenticated: z.boolean(),
        can_search: z.boolean(),
        categories: z.array(z.object({
            id: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]),
            name: z.string(),
            icon: z.string()
        })),
        features: z.object({
            ai: z.boolean(),
            searxng_api: z.boolean()
        }),
        engines: z.array(z.object({
            slug: z.string(),
            name: z.string(),
            categories: z.array(z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]))
        })),
        instant_answer_providers: z.array(z.object({
            id: z.string(),
            name: z.string(),
            description: z.string(),
            examples: z.array(z.string())
        })),
        autocomplete_providers: z.array(z.object({
            id: z.string(),
            name: z.string()
        })),
        search_defaults: z.object({
            default_category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]),
            language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/),
            safesearch: z.union([
                z.literal(0),
                z.literal(1),
                z.literal(2)
            ]),
            open_in_new_tab: z.boolean(),
            image_proxy: z.boolean(),
            autocomplete: z.enum([
                'none',
                'duckduckgo',
                'google',
                'brave',
                'wikipedia'
            ]),
            bangs_enabled: z.boolean(),
            ddg_bangs_enabled: z.boolean(),
            instant_answers_enabled: z.boolean(),
            disabled_instant_answers: z.array(z.string().max(64)).max(100),
            ai_mode: z.enum([
                'off',
                'manual',
                'auto'
            ]),
            disabled_engines: z.array(z.string().max(64)).max(200),
            units: z.enum(['metric', 'imperial'])
        })
    })
});

export const zGetSearchQuery = z.object({
    q: z.string().min(1).max(500),
    category: z.enum([
        'general',
        'images',
        'news',
        'videos'
    ]).optional(),
    page: z.int().gte(1).lte(20).optional().default(1),
    language: z.string().regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/).optional(),
    safesearch: z.int().gte(0).lte(2).optional(),
    time_range: z.enum([
        'day',
        'week',
        'month',
        'year'
    ]).optional(),
    engines: z.string().max(500).optional()
});

/**
 * Search completed
 */
export const zGetSearchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Search completed'),
    data: z.object({
        query: z.string(),
        raw_query: z.string(),
        category: z.enum([
            'general',
            'images',
            'news',
            'videos'
        ]),
        page: z.number(),
        redirect: z.object({
            url: z.string(),
            bang: z.object({
                trigger: z.string(),
                name: z.string(),
                source: z.enum([
                    'user',
                    'instance',
                    'ddg',
                    'internal'
                ])
            })
        }).nullable(),
        category_redirect: z.enum([
            'general',
            'images',
            'news',
            'videos'
        ]).nullable(),
        results: z.array(z.object({
            url: z.string(),
            title: z.string(),
            content: z.string(),
            template: z.enum([
                'web',
                'image',
                'video',
                'news'
            ]),
            category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]),
            engines: z.array(z.string()),
            positions: z.array(z.number()),
            score: z.number(),
            published_at: z.number().nullable(),
            thumbnail: z.string().nullable(),
            img_src: z.string().nullable(),
            width: z.number().nullable(),
            height: z.number().nullable(),
            source: z.string().nullable(),
            author: z.string().nullable(),
            duration: z.string().nullable(),
            embed_url: z.string().nullable(),
            views: z.number().nullable()
        })),
        instant_answers: z.array(z.object({
            provider: z.string(),
            type: z.string(),
            placement: z.enum(['top', 'side']),
            title: z.string(),
            text: z.string(),
            data: z.record(z.string(), z.unknown()),
            source: z.object({
                name: z.string(),
                url: z.string().nullable()
            }).nullable()
        })),
        suggestions: z.array(z.string()),
        corrections: z.array(z.string()),
        engines: z.array(z.object({
            slug: z.string(),
            name: z.string(),
            status: z.enum([
                'ok',
                'error',
                'timeout',
                'blocked',
                'suspended',
                'throttled'
            ]),
            time_ms: z.number(),
            results: z.number(),
            error: z.string().nullable(),
            cached: z.enum(['fresh', 'stale']).nullable(),
            fallback: z.boolean()
        })),
        number_of_results: z.number(),
        time_ms: z.number(),
        cached: z.boolean(),
        ai_available: z.boolean()
    })
});

export const zGetSearchAutocompleteQuery = z.object({
    q: z.string().max(200)
});

/**
 * Suggestions retrieved
 */
export const zGetSearchAutocompleteResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Suggestions retrieved'),
    data: z.object({
        suggestions: z.array(z.string()),
        bangs: z.array(z.object({
            trigger: z.string(),
            name: z.string(),
            domain: z.string(),
            category: z.string().nullable(),
            source: z.enum([
                'user',
                'instance',
                'internal',
                'ddg'
            ]),
            switches_category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]).nullable()
        }))
    })
});

export const zGetSearchSuggestOpensearchQuery = z.object({
    q: z.string().max(200)
});

export const zPostSearchAiBody = z.object({
    q: z.string().min(1).max(500),
    language: z.string().regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/).optional(),
    stream: z.boolean().optional().default(true)
});

/**
 * AI answer generated
 */
export const zPostSearchAiResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('AI answer generated'),
    data: z.object({
        answer: z.string(),
        model: z.string().nullable(),
        sources: z.array(z.object({
            index: z.number(),
            title: z.string(),
            url: z.string()
        }))
    })
});

/**
 * Chats retrieved
 */
export const zGetAiChatsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Chats retrieved'),
    data: z.array(z.object({
        id: z.number(),
        title: z.string(),
        created_at: z.number(),
        updated_at: z.number()
    }))
});

export const zPostAiChatsBody = z.object({
    messages: z.array(z.object({
        role: z.enum(['user', 'assistant']),
        content: z.string().min(1).max(20000),
        sources: z.array(z.object({
            index: z.int().gte(1).lte(100),
            title: z.string().max(1000),
            url: z.string().max(4096)
        })).max(20).optional().default([])
    })).max(20).optional().default([])
});

/**
 * Chat created
 */
export const zPostAiChatsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Chat created'),
    data: z.object({
        id: z.number(),
        title: z.string(),
        created_at: z.number(),
        updated_at: z.number()
    })
});

export const zDeleteAiChatsByChatIdPath = z.object({
    chatID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Chat deleted
 */
export const zDeleteAiChatsByChatIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Chat deleted'),
    data: z.null()
});

export const zGetAiChatsByChatIdPath = z.object({
    chatID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Chat retrieved
 */
export const zGetAiChatsByChatIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Chat retrieved'),
    data: z.object({
        id: z.number(),
        title: z.string(),
        created_at: z.number(),
        updated_at: z.number(),
        messages: z.array(z.object({
            id: z.number(),
            role: z.enum(['user', 'assistant']),
            content: z.string(),
            sources: z.array(z.object({
                index: z.int().gte(1).lte(100),
                title: z.string().max(1000),
                url: z.string().max(4096)
            })),
            search_query: z.string().nullable(),
            created_at: z.number()
        }))
    })
});

export const zPostAiChatsByChatIdMessagesBody = z.object({
    content: z.string().min(1).max(2000),
    language: z.string().regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/).optional(),
    stream: z.boolean().optional().default(true)
});

export const zPostAiChatsByChatIdMessagesPath = z.object({
    chatID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Answer generated
 */
export const zPostAiChatsByChatIdMessagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Answer generated'),
    data: z.object({
        message: z.object({
            id: z.number(),
            role: z.enum(['user', 'assistant']),
            content: z.string(),
            sources: z.array(z.object({
                index: z.int().gte(1).lte(100),
                title: z.string().max(1000),
                url: z.string().max(4096)
            })),
            search_query: z.string().nullable(),
            created_at: z.number()
        }),
        model: z.string().nullable(),
        chat: z.object({
            id: z.number(),
            title: z.string(),
            created_at: z.number(),
            updated_at: z.number()
        })
    })
});

export const zGetBangsSuggestQuery = z.object({
    q: z.string().min(1).max(64),
    limit: z.int().gte(1).lte(25).optional().default(8)
});

/**
 * Bangs retrieved
 */
export const zGetBangsSuggestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Bangs retrieved'),
    data: z.array(z.object({
        trigger: z.string(),
        name: z.string(),
        domain: z.string(),
        category: z.string().nullable(),
        source: z.enum([
            'user',
            'instance',
            'internal',
            'ddg'
        ]),
        switches_category: z.enum([
            'general',
            'images',
            'news',
            'videos'
        ]).nullable()
    }))
});

export const zGetBangsResolveQuery = z.object({
    q: z.string().min(1).max(500)
});

/**
 * Bang resolved
 */
export const zGetBangsResolveResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Bang resolved'),
    data: z.object({
        kind: z.enum([
            'redirect',
            'category',
            'lucky',
            'none'
        ]),
        url: z.string().nullable(),
        category: z.enum([
            'general',
            'images',
            'news',
            'videos'
        ]).nullable(),
        query: z.string(),
        bang: z.object({
            trigger: z.string(),
            name: z.string(),
            source: z.enum([
                'user',
                'instance',
                'internal',
                'ddg'
            ])
        }).nullable()
    })
});

export const zGetProxyImageQuery = z.object({
    url: z.string().min(1).max(4096),
    sig: z.string().length(32)
});

export const zGetProxyFaviconQuery = z.object({
    domain: z.string().max(253).regex(/^(?=.{1,253}$)([a-z0-9-]{1,63}\.)+[a-z]{2,63}$/)
});

export const zPostAuthLoginBody = z.object({
    username: z.string(),
    password: z.string()
});

/**
 * Login successful
 */
export const zPostAuthLoginResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Login successful'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        token: z.string()
    })
});

/**
 * Session info retrieved successfully
 */
export const zGetAuthSessionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Session info retrieved successfully'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

/**
 * Logout successful
 */
export const zPostAuthLogoutResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Logout successful'),
    data: z.null()
});

export const zPostAuthResetPasswordBody = z.object({
    reset_token: z.string().min(1),
    new_password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
});

/**
 * Password has been reset successfully
 */
export const zPostAuthResetPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password has been reset successfully'),
    data: z.null()
});

export const zPostAuthResetPasswordRequestBody = z.object({
    email: z.email().regex(/^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/)
});

/**
 * If the username exists, a password reset has been requested
 */
export const zPostAuthResetPasswordRequestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('If the username exists, a password reset has been requested'),
    data: z.null()
});

/**
 * Account deleted successfully
 */
export const zDeleteAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account deleted successfully'),
    data: z.null()
});

/**
 * Account information retrieved successfully
 */
export const zGetAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zPutAccountBody = z.object({
    username: z.string().min(5).max(40).regex(/^(?!.*[.-]{2})(?!.*--)(?!.*\.\.)[a-z0-9](?:[a-z0-9._-]{3,38}[a-z0-9_])?$/).optional(),
    display_name: z.string().optional(),
    email: z.email().regex(/^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/).optional(),
    current_password: z.string().min(1)
});

/**
 * Account information updated successfully
 */
export const zPutAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information updated successfully'),
    data: z.null()
});

export const zPutAccountPasswordBody = z.object({
    current_password: z.string(),
    new_password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
});

/**
 * Password changed successfully
 */
export const zPutAccountPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password changed successfully'),
    data: z.null()
});

/**
 * API keys retrieved successfully
 */
export const zGetAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API keys retrieved successfully'),
    data: z.array(z.object({
        id: z.string(),
        description: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable()
    }))
});

export const zPostAccountApikeysBody = z.object({
    description: z.string().min(1).max(255),
    expires_at: z.union([
        z.literal('7d'),
        z.literal('30d'),
        z.literal('90d'),
        z.literal('180d'),
        z.literal('365d')
    ]).nullable()
});

/**
 * API key created successfully
 */
export const zPostAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key created successfully'),
    data: z.object({
        id: z.string(),
        token: z.string()
    })
});

export const zDeleteAccountApikeysByApiKeyIdPath = z.object({
    apiKeyID: z.string().min(1).max(255)
});

/**
 * API key deleted successfully
 */
export const zDeleteAccountApikeysByApiKeyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key deleted successfully'),
    data: z.null()
});

export const zGetAccountApikeysByApiKeyIdPath = z.object({
    apiKeyID: z.string().min(1).max(255)
});

/**
 * API key retrieved successfully
 */
export const zGetAccountApikeysByApiKeyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key retrieved successfully'),
    data: z.object({
        id: z.string(),
        description: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable()
    })
});

/**
 * Preferences retrieved successfully
 */
export const zGetAccountPreferencesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Preferences retrieved successfully'),
    data: z.object({
        search: z.object({
            default_category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]).optional(),
            language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/).optional(),
            safesearch: z.union([
                z.literal(0),
                z.literal(1),
                z.literal(2)
            ]).optional(),
            open_in_new_tab: z.boolean().optional(),
            image_proxy: z.boolean().optional(),
            autocomplete: z.enum([
                'none',
                'duckduckgo',
                'google',
                'brave',
                'wikipedia'
            ]).optional(),
            bangs_enabled: z.boolean().optional(),
            ddg_bangs_enabled: z.boolean().optional(),
            instant_answers_enabled: z.boolean().optional(),
            disabled_instant_answers: z.array(z.string().max(64)).max(100).optional(),
            ai_mode: z.enum([
                'off',
                'manual',
                'auto'
            ]).optional(),
            disabled_engines: z.array(z.string().max(64)).max(200).optional(),
            units: z.enum(['metric', 'imperial']).optional()
        })
    })
});

/**
 * Search preferences retrieved
 */
export const zGetAccountPreferencesSearchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Search preferences retrieved'),
    data: z.object({
        defaults: z.object({
            default_category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]),
            language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/),
            safesearch: z.union([
                z.literal(0),
                z.literal(1),
                z.literal(2)
            ]),
            open_in_new_tab: z.boolean(),
            image_proxy: z.boolean(),
            autocomplete: z.enum([
                'none',
                'duckduckgo',
                'google',
                'brave',
                'wikipedia'
            ]),
            bangs_enabled: z.boolean(),
            ddg_bangs_enabled: z.boolean(),
            instant_answers_enabled: z.boolean(),
            disabled_instant_answers: z.array(z.string().max(64)).max(100),
            ai_mode: z.enum([
                'off',
                'manual',
                'auto'
            ]),
            disabled_engines: z.array(z.string().max(64)).max(200),
            units: z.enum(['metric', 'imperial'])
        }),
        overrides: z.object({
            default_category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]).optional(),
            language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/).optional(),
            safesearch: z.union([
                z.literal(0),
                z.literal(1),
                z.literal(2)
            ]).optional(),
            open_in_new_tab: z.boolean().optional(),
            image_proxy: z.boolean().optional(),
            autocomplete: z.enum([
                'none',
                'duckduckgo',
                'google',
                'brave',
                'wikipedia'
            ]).optional(),
            bangs_enabled: z.boolean().optional(),
            ddg_bangs_enabled: z.boolean().optional(),
            instant_answers_enabled: z.boolean().optional(),
            disabled_instant_answers: z.array(z.string().max(64)).max(100).optional(),
            ai_mode: z.enum([
                'off',
                'manual',
                'auto'
            ]).optional(),
            disabled_engines: z.array(z.string().max(64)).max(200).optional(),
            units: z.enum(['metric', 'imperial']).optional()
        }),
        effective: z.object({
            default_category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]),
            language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/),
            safesearch: z.union([
                z.literal(0),
                z.literal(1),
                z.literal(2)
            ]),
            open_in_new_tab: z.boolean(),
            image_proxy: z.boolean(),
            autocomplete: z.enum([
                'none',
                'duckduckgo',
                'google',
                'brave',
                'wikipedia'
            ]),
            bangs_enabled: z.boolean(),
            ddg_bangs_enabled: z.boolean(),
            instant_answers_enabled: z.boolean(),
            disabled_instant_answers: z.array(z.string().max(64)).max(100),
            ai_mode: z.enum([
                'off',
                'manual',
                'auto'
            ]),
            disabled_engines: z.array(z.string().max(64)).max(200),
            units: z.enum(['metric', 'imperial'])
        })
    })
});

export const zPutAccountPreferencesSearchBody = z.object({
    default_category: z.enum([
        'general',
        'images',
        'news',
        'videos'
    ]).optional(),
    language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/).optional(),
    safesearch: z.union([
        z.literal(0),
        z.literal(1),
        z.literal(2)
    ]).optional(),
    open_in_new_tab: z.boolean().optional(),
    image_proxy: z.boolean().optional(),
    autocomplete: z.enum([
        'none',
        'duckduckgo',
        'google',
        'brave',
        'wikipedia'
    ]).optional(),
    bangs_enabled: z.boolean().optional(),
    ddg_bangs_enabled: z.boolean().optional(),
    instant_answers_enabled: z.boolean().optional(),
    disabled_instant_answers: z.array(z.string().max(64)).max(100).optional(),
    ai_mode: z.enum([
        'off',
        'manual',
        'auto'
    ]).optional(),
    disabled_engines: z.array(z.string().max(64)).max(200).optional(),
    units: z.enum(['metric', 'imperial']).optional()
});

/**
 * Search preferences updated
 */
export const zPutAccountPreferencesSearchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Search preferences updated'),
    data: z.object({
        defaults: z.object({
            default_category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]),
            language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/),
            safesearch: z.union([
                z.literal(0),
                z.literal(1),
                z.literal(2)
            ]),
            open_in_new_tab: z.boolean(),
            image_proxy: z.boolean(),
            autocomplete: z.enum([
                'none',
                'duckduckgo',
                'google',
                'brave',
                'wikipedia'
            ]),
            bangs_enabled: z.boolean(),
            ddg_bangs_enabled: z.boolean(),
            instant_answers_enabled: z.boolean(),
            disabled_instant_answers: z.array(z.string().max(64)).max(100),
            ai_mode: z.enum([
                'off',
                'manual',
                'auto'
            ]),
            disabled_engines: z.array(z.string().max(64)).max(200),
            units: z.enum(['metric', 'imperial'])
        }),
        overrides: z.object({
            default_category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]).optional(),
            language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/).optional(),
            safesearch: z.union([
                z.literal(0),
                z.literal(1),
                z.literal(2)
            ]).optional(),
            open_in_new_tab: z.boolean().optional(),
            image_proxy: z.boolean().optional(),
            autocomplete: z.enum([
                'none',
                'duckduckgo',
                'google',
                'brave',
                'wikipedia'
            ]).optional(),
            bangs_enabled: z.boolean().optional(),
            ddg_bangs_enabled: z.boolean().optional(),
            instant_answers_enabled: z.boolean().optional(),
            disabled_instant_answers: z.array(z.string().max(64)).max(100).optional(),
            ai_mode: z.enum([
                'off',
                'manual',
                'auto'
            ]).optional(),
            disabled_engines: z.array(z.string().max(64)).max(200).optional(),
            units: z.enum(['metric', 'imperial']).optional()
        }),
        effective: z.object({
            default_category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]),
            language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/),
            safesearch: z.union([
                z.literal(0),
                z.literal(1),
                z.literal(2)
            ]),
            open_in_new_tab: z.boolean(),
            image_proxy: z.boolean(),
            autocomplete: z.enum([
                'none',
                'duckduckgo',
                'google',
                'brave',
                'wikipedia'
            ]),
            bangs_enabled: z.boolean(),
            ddg_bangs_enabled: z.boolean(),
            instant_answers_enabled: z.boolean(),
            disabled_instant_answers: z.array(z.string().max(64)).max(100),
            ai_mode: z.enum([
                'off',
                'manual',
                'auto'
            ]),
            disabled_engines: z.array(z.string().max(64)).max(200),
            units: z.enum(['metric', 'imperial'])
        })
    })
});

/**
 * Bangs retrieved
 */
export const zGetAccountBangsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Bangs retrieved'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        trigger: z.string(),
        name: z.string(),
        url_template: z.string(),
        category: z.string().nullable(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    }))
});

export const zPostAccountBangsBody = z.object({
    trigger: z.string().regex(/^!?[a-z0-9][a-z0-9._+-]{0,31}$/),
    name: z.string().min(1).max(64),
    url_template: z.string().max(2048),
    category: z.string().max(64).nullish().default(null)
});

/**
 * Bang created
 */
export const zPostAccountBangsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Bang created'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        trigger: z.string(),
        name: z.string(),
        url_template: z.string(),
        category: z.string().nullable(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zDeleteAccountBangsByBangIdPath = z.object({
    bangID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Bang deleted
 */
export const zDeleteAccountBangsByBangIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Bang deleted'),
    data: z.null()
});

export const zPutAccountBangsByBangIdBody = z.object({
    trigger: z.string().regex(/^!?[a-z0-9][a-z0-9._+-]{0,31}$/),
    name: z.string().min(1).max(64),
    url_template: z.string().max(2048),
    category: z.string().max(64).nullish().default(null)
});

export const zPutAccountBangsByBangIdPath = z.object({
    bangID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Bang updated
 */
export const zPutAccountBangsByBangIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Bang updated'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        trigger: z.string(),
        name: z.string(),
        url_template: z.string(),
        category: z.string().nullable(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zGetAdminUsersQuery = z.object({
    role: z.enum(['admin', 'user']).optional(),
    search: z.string().min(1).max(64).optional(),
    limit: z.int().gte(1).lte(100).optional(),
    offset: z.int().gte(0).lte(9007199254740991).optional()
});

/**
 * Users retrieved successfully
 */
export const zGetAdminUsersResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Users retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    }))
});

export const zPostAdminUsersBody = z.object({
    username: z.string().min(5).max(40).regex(/^(?!.*[.-]{2})(?!.*--)(?!.*\.\.)[a-z0-9](?:[a-z0-9._-]{3,38}[a-z0-9_])?$/),
    display_name: z.string().min(1).max(64),
    email: z.email().regex(/^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
    role: z.enum(['admin', 'user']).optional(),
    password: z.string().min(8).max(128)
});

/**
 * User created successfully
 */
export const zPostAdminUsersResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('User created successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zDeleteAdminUsersByUserIdPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * User deleted successfully
 */
export const zDeleteAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User deleted successfully'),
    data: z.null()
});

export const zGetAdminUsersByUserIdPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * User retrieved successfully
 */
export const zGetAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zPutAdminUsersByUserIdBody = z.object({
    username: z.string().optional(),
    display_name: z.string().optional(),
    email: z.string().optional(),
    role: z.enum(['admin', 'user']).optional()
});

export const zPutAdminUsersByUserIdPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * User updated successfully
 */
export const zPutAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User updated successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zPutAdminUsersByUserIdPasswordBody = z.object({
    password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
});

export const zPutAdminUsersByUserIdPasswordPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * Password reset successfully
 */
export const zPutAdminUsersByUserIdPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password reset successfully'),
    data: z.null()
});

/**
 * Engine types retrieved
 */
export const zGetAdminEnginesTypesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Engine types retrieved'),
    data: z.array(z.object({
        type: z.string(),
        name: z.string(),
        description: z.string(),
        website: z.string(),
        categories: z.array(z.enum([
            'general',
            'images',
            'news',
            'videos'
        ])),
        features: z.object({
            paging: z.boolean(),
            timeRange: z.boolean(),
            safeSearch: z.boolean(),
            language: z.boolean()
        }),
        settings_schema: z.record(z.string(), z.unknown()),
        default_settings: z.record(z.string(), z.unknown()),
        secret_fields: z.array(z.string()),
        requires_configuration: z.boolean(),
        default_timeout_ms: z.number(),
        default_rate_limit_per_minute: z.number()
    }))
});

/**
 * Engines retrieved
 */
export const zGetAdminEnginesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Engines retrieved'),
    data: z.array(z.object({
        id: z.number(),
        slug: z.string(),
        name: z.string(),
        engine_type: z.string(),
        enabled: z.boolean(),
        categories: z.array(z.enum([
            'general',
            'images',
            'news',
            'videos'
        ])),
        weight: z.number(),
        timeout_ms: z.number(),
        proxy_ids: z.array(z.number()),
        fallback: z.boolean(),
        rate_limit_per_minute: z.number(),
        settings: z.record(z.string(), z.unknown()),
        secrets_set: z.array(z.string()),
        created_at: z.number(),
        health: z.object({
            suspended_until: z.number().nullable(),
            consecutive_failures: z.number(),
            last_error: z.string().nullable(),
            last_error_at: z.number().nullable(),
            last_success_at: z.number().nullable(),
            last_latency_ms: z.number().nullable(),
            requests_last_minute: z.number()
        }),
        load_error: z.string().nullable()
    }))
});

export const zPostAdminEnginesBody = z.object({
    slug: z.string().regex(/^[a-z0-9][a-z0-9-]{1,47}$/),
    name: z.string().min(1).max(64),
    engine_type: z.string().min(1).max(64),
    enabled: z.boolean().optional().default(true),
    categories: z.array(z.enum([
        'general',
        'images',
        'news',
        'videos'
    ])).min(1),
    weight: z.number().gte(0).lte(10).optional().default(1),
    timeout_ms: z.int().gte(500).lte(30000).optional().default(4000),
    proxy_ids: z.array(z.int().gt(0).lte(9007199254740991)).max(50).optional().default([]),
    fallback: z.boolean().optional().default(false),
    rate_limit_per_minute: z.int().gte(0).lte(10000).optional(),
    settings: z.record(z.string(), z.unknown()).optional().default({})
});

/**
 * Engine created
 */
export const zPostAdminEnginesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Engine created'),
    data: z.object({
        id: z.number(),
        slug: z.string(),
        name: z.string(),
        engine_type: z.string(),
        enabled: z.boolean(),
        categories: z.array(z.enum([
            'general',
            'images',
            'news',
            'videos'
        ])),
        weight: z.number(),
        timeout_ms: z.number(),
        proxy_ids: z.array(z.number()),
        fallback: z.boolean(),
        rate_limit_per_minute: z.number(),
        settings: z.record(z.string(), z.unknown()),
        secrets_set: z.array(z.string()),
        created_at: z.number(),
        health: z.object({
            suspended_until: z.number().nullable(),
            consecutive_failures: z.number(),
            last_error: z.string().nullable(),
            last_error_at: z.number().nullable(),
            last_success_at: z.number().nullable(),
            last_latency_ms: z.number().nullable(),
            requests_last_minute: z.number()
        }),
        load_error: z.string().nullable()
    })
});

export const zDeleteAdminEnginesByEngineIdPath = z.object({
    engineID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Engine deleted
 */
export const zDeleteAdminEnginesByEngineIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Engine deleted'),
    data: z.null()
});

export const zGetAdminEnginesByEngineIdPath = z.object({
    engineID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Engine retrieved
 */
export const zGetAdminEnginesByEngineIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Engine retrieved'),
    data: z.object({
        id: z.number(),
        slug: z.string(),
        name: z.string(),
        engine_type: z.string(),
        enabled: z.boolean(),
        categories: z.array(z.enum([
            'general',
            'images',
            'news',
            'videos'
        ])),
        weight: z.number(),
        timeout_ms: z.number(),
        proxy_ids: z.array(z.number()),
        fallback: z.boolean(),
        rate_limit_per_minute: z.number(),
        settings: z.record(z.string(), z.unknown()),
        secrets_set: z.array(z.string()),
        created_at: z.number(),
        health: z.object({
            suspended_until: z.number().nullable(),
            consecutive_failures: z.number(),
            last_error: z.string().nullable(),
            last_error_at: z.number().nullable(),
            last_success_at: z.number().nullable(),
            last_latency_ms: z.number().nullable(),
            requests_last_minute: z.number()
        }),
        load_error: z.string().nullable()
    })
});

export const zPutAdminEnginesByEngineIdBody = z.object({
    slug: z.string().regex(/^[a-z0-9][a-z0-9-]{1,47}$/).optional(),
    name: z.string().min(1).max(64).optional(),
    enabled: z.boolean().optional(),
    categories: z.array(z.enum([
        'general',
        'images',
        'news',
        'videos'
    ])).min(1).optional(),
    weight: z.number().gte(0).lte(10).optional(),
    timeout_ms: z.int().gte(500).lte(30000).optional(),
    proxy_ids: z.array(z.int().gt(0).lte(9007199254740991)).max(50).optional(),
    fallback: z.boolean().optional(),
    rate_limit_per_minute: z.int().gte(0).lte(10000).optional(),
    settings: z.record(z.string(), z.unknown()).optional()
});

export const zPutAdminEnginesByEngineIdPath = z.object({
    engineID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Engine updated
 */
export const zPutAdminEnginesByEngineIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Engine updated'),
    data: z.object({
        id: z.number(),
        slug: z.string(),
        name: z.string(),
        engine_type: z.string(),
        enabled: z.boolean(),
        categories: z.array(z.enum([
            'general',
            'images',
            'news',
            'videos'
        ])),
        weight: z.number(),
        timeout_ms: z.number(),
        proxy_ids: z.array(z.number()),
        fallback: z.boolean(),
        rate_limit_per_minute: z.number(),
        settings: z.record(z.string(), z.unknown()),
        secrets_set: z.array(z.string()),
        created_at: z.number(),
        health: z.object({
            suspended_until: z.number().nullable(),
            consecutive_failures: z.number(),
            last_error: z.string().nullable(),
            last_error_at: z.number().nullable(),
            last_success_at: z.number().nullable(),
            last_latency_ms: z.number().nullable(),
            requests_last_minute: z.number()
        }),
        load_error: z.string().nullable()
    })
});

export const zPostAdminEnginesByEngineIdTestBody = z.object({
    query: z.string().min(1).max(200).optional().default('open source'),
    category: z.enum([
        'general',
        'images',
        'news',
        'videos'
    ]).optional()
});

export const zPostAdminEnginesByEngineIdTestPath = z.object({
    engineID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Engine tested
 */
export const zPostAdminEnginesByEngineIdTestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Engine tested'),
    data: z.object({
        ok: z.boolean(),
        status: z.enum([
            'ok',
            'error',
            'timeout',
            'blocked',
            'suspended',
            'throttled'
        ]),
        time_ms: z.number(),
        results: z.number(),
        error: z.string().nullable(),
        sample: z.array(z.object({
            url: z.string(),
            title: z.string(),
            content: z.string(),
            template: z.enum([
                'web',
                'image',
                'video',
                'news'
            ]),
            category: z.enum([
                'general',
                'images',
                'news',
                'videos'
            ]),
            engines: z.array(z.string()),
            positions: z.array(z.number()),
            score: z.number(),
            published_at: z.number().nullable(),
            thumbnail: z.string().nullable(),
            img_src: z.string().nullable(),
            width: z.number().nullable(),
            height: z.number().nullable(),
            source: z.string().nullable(),
            author: z.string().nullable(),
            duration: z.string().nullable(),
            embed_url: z.string().nullable(),
            views: z.number().nullable()
        }))
    })
});

/**
 * Proxy types retrieved
 */
export const zGetAdminProxiesTypesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Proxy types retrieved'),
    data: z.array(z.object({
        type: z.string(),
        name: z.string(),
        description: z.string(),
        settings_schema: z.record(z.string(), z.unknown()),
        default_settings: z.record(z.string(), z.unknown()),
        secret_fields: z.array(z.string())
    }))
});

export const zPostAdminProxiesTestBody = z.object({
    proxy_type: z.string().min(1).max(64),
    settings: z.record(z.string(), z.unknown()).optional().default({})
});

/**
 * Proxy tested
 */
export const zPostAdminProxiesTestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Proxy tested'),
    data: z.object({
        ok: z.boolean(),
        latency_ms: z.number(),
        status: z.number().nullable(),
        ip: z.string().nullable(),
        error: z.string().nullable()
    })
});

/**
 * Proxies retrieved
 */
export const zGetAdminProxiesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Proxies retrieved'),
    data: z.array(z.object({
        id: z.number(),
        name: z.string(),
        proxy_type: z.string(),
        enabled: z.boolean(),
        settings: z.record(z.string(), z.unknown()),
        secrets_set: z.array(z.string()),
        created_at: z.number(),
        used_by_engines: z.array(z.string()),
        is_default: z.boolean()
    }))
});

export const zPostAdminProxiesBody = z.object({
    name: z.string().min(1).max(64),
    proxy_type: z.string().min(1).max(64),
    enabled: z.boolean().optional().default(true),
    settings: z.record(z.string(), z.unknown()).optional().default({})
});

/**
 * Proxy created
 */
export const zPostAdminProxiesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Proxy created'),
    data: z.object({
        id: z.number(),
        name: z.string(),
        proxy_type: z.string(),
        enabled: z.boolean(),
        settings: z.record(z.string(), z.unknown()),
        secrets_set: z.array(z.string()),
        created_at: z.number(),
        used_by_engines: z.array(z.string()),
        is_default: z.boolean()
    })
});

export const zDeleteAdminProxiesByProxyIdPath = z.object({
    proxyID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Proxy deleted
 */
export const zDeleteAdminProxiesByProxyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Proxy deleted'),
    data: z.null()
});

export const zGetAdminProxiesByProxyIdPath = z.object({
    proxyID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Proxy retrieved
 */
export const zGetAdminProxiesByProxyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Proxy retrieved'),
    data: z.object({
        id: z.number(),
        name: z.string(),
        proxy_type: z.string(),
        enabled: z.boolean(),
        settings: z.record(z.string(), z.unknown()),
        secrets_set: z.array(z.string()),
        created_at: z.number(),
        used_by_engines: z.array(z.string()),
        is_default: z.boolean()
    })
});

export const zPutAdminProxiesByProxyIdBody = z.object({
    name: z.string().min(1).max(64).optional(),
    enabled: z.boolean().optional().default(true),
    settings: z.record(z.string(), z.unknown()).optional().default({})
});

export const zPutAdminProxiesByProxyIdPath = z.object({
    proxyID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Proxy updated
 */
export const zPutAdminProxiesByProxyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Proxy updated'),
    data: z.object({
        id: z.number(),
        name: z.string(),
        proxy_type: z.string(),
        enabled: z.boolean(),
        settings: z.record(z.string(), z.unknown()),
        secrets_set: z.array(z.string()),
        created_at: z.number(),
        used_by_engines: z.array(z.string()),
        is_default: z.boolean()
    })
});

export const zPostAdminProxiesByProxyIdTestPath = z.object({
    proxyID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Proxy tested
 */
export const zPostAdminProxiesByProxyIdTestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Proxy tested'),
    data: z.object({
        ok: z.boolean(),
        latency_ms: z.number(),
        status: z.number().nullable(),
        ip: z.string().nullable(),
        error: z.string().nullable()
    })
});

/**
 * Instance settings retrieved
 */
export const zGetAdminSettingsInstanceResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instance settings retrieved'),
    data: z.object({
        instance_name: z.string().min(1).max(64),
        search_access: z.enum(['authenticated', 'public']),
        searxng_api_enabled: z.boolean(),
        searxng_api_require_key: z.boolean(),
        default_proxy_ids: z.array(z.int().gt(0).lte(9007199254740991)),
        ddg_bangs_auto_update: z.boolean(),
        ddg_bangs_update_interval_hours: z.int().gte(1).lte(2160),
        public_rate_limit_per_minute: z.int().gte(0).lte(10000),
        search_cache_ttl_minutes: z.int().gte(0).lte(10080),
        news_cache_ttl_minutes: z.int().gte(0).lte(1440),
        search_cache_stale_hours: z.int().gte(0).lte(720),
        search_cache_persistent: z.boolean(),
        min_healthy_engines: z.int().gte(1).lte(20)
    })
});

export const zPutAdminSettingsInstanceBody = z.object({
    instance_name: z.string().min(1).max(64).optional(),
    search_access: z.enum(['authenticated', 'public']).optional(),
    searxng_api_enabled: z.boolean().optional(),
    searxng_api_require_key: z.boolean().optional(),
    default_proxy_ids: z.array(z.int().gt(0).lte(9007199254740991)).optional(),
    ddg_bangs_auto_update: z.boolean().optional(),
    ddg_bangs_update_interval_hours: z.int().gte(1).lte(2160).optional(),
    public_rate_limit_per_minute: z.int().gte(0).lte(10000).optional(),
    search_cache_ttl_minutes: z.int().gte(0).lte(10080).optional(),
    news_cache_ttl_minutes: z.int().gte(0).lte(1440).optional(),
    search_cache_stale_hours: z.int().gte(0).lte(720).optional(),
    search_cache_persistent: z.boolean().optional(),
    min_healthy_engines: z.int().gte(1).lte(20).optional()
});

/**
 * Instance settings updated
 */
export const zPutAdminSettingsInstanceResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instance settings updated'),
    data: z.object({
        instance_name: z.string().min(1).max(64),
        search_access: z.enum(['authenticated', 'public']),
        searxng_api_enabled: z.boolean(),
        searxng_api_require_key: z.boolean(),
        default_proxy_ids: z.array(z.int().gt(0).lte(9007199254740991)),
        ddg_bangs_auto_update: z.boolean(),
        ddg_bangs_update_interval_hours: z.int().gte(1).lte(2160),
        public_rate_limit_per_minute: z.int().gte(0).lte(10000),
        search_cache_ttl_minutes: z.int().gte(0).lte(10080),
        news_cache_ttl_minutes: z.int().gte(0).lte(1440),
        search_cache_stale_hours: z.int().gte(0).lte(720),
        search_cache_persistent: z.boolean(),
        min_healthy_engines: z.int().gte(1).lte(20)
    })
});

/**
 * Search defaults retrieved
 */
export const zGetAdminSettingsSearchDefaultsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Search defaults retrieved'),
    data: z.object({
        default_category: z.enum([
            'general',
            'images',
            'news',
            'videos'
        ]),
        language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/),
        safesearch: z.union([
            z.literal(0),
            z.literal(1),
            z.literal(2)
        ]),
        open_in_new_tab: z.boolean(),
        image_proxy: z.boolean(),
        autocomplete: z.enum([
            'none',
            'duckduckgo',
            'google',
            'brave',
            'wikipedia'
        ]),
        bangs_enabled: z.boolean(),
        ddg_bangs_enabled: z.boolean(),
        instant_answers_enabled: z.boolean(),
        disabled_instant_answers: z.array(z.string().max(64)).max(100),
        ai_mode: z.enum([
            'off',
            'manual',
            'auto'
        ]),
        disabled_engines: z.array(z.string().max(64)).max(200),
        units: z.enum(['metric', 'imperial'])
    })
});

export const zPutAdminSettingsSearchDefaultsBody = z.object({
    default_category: z.enum([
        'general',
        'images',
        'news',
        'videos'
    ]).optional(),
    language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/).optional(),
    safesearch: z.union([
        z.literal(0),
        z.literal(1),
        z.literal(2)
    ]).optional(),
    open_in_new_tab: z.boolean().optional(),
    image_proxy: z.boolean().optional(),
    autocomplete: z.enum([
        'none',
        'duckduckgo',
        'google',
        'brave',
        'wikipedia'
    ]).optional(),
    bangs_enabled: z.boolean().optional(),
    ddg_bangs_enabled: z.boolean().optional(),
    instant_answers_enabled: z.boolean().optional(),
    disabled_instant_answers: z.array(z.string().max(64)).max(100).optional(),
    ai_mode: z.enum([
        'off',
        'manual',
        'auto'
    ]).optional(),
    disabled_engines: z.array(z.string().max(64)).max(200).optional(),
    units: z.enum(['metric', 'imperial']).optional()
});

/**
 * Search defaults updated
 */
export const zPutAdminSettingsSearchDefaultsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Search defaults updated'),
    data: z.object({
        default_category: z.enum([
            'general',
            'images',
            'news',
            'videos'
        ]),
        language: z.string().min(2).max(16).regex(/^(all|[a-z]{2,3}(-[A-Za-z]{2,4})?)$/),
        safesearch: z.union([
            z.literal(0),
            z.literal(1),
            z.literal(2)
        ]),
        open_in_new_tab: z.boolean(),
        image_proxy: z.boolean(),
        autocomplete: z.enum([
            'none',
            'duckduckgo',
            'google',
            'brave',
            'wikipedia'
        ]),
        bangs_enabled: z.boolean(),
        ddg_bangs_enabled: z.boolean(),
        instant_answers_enabled: z.boolean(),
        disabled_instant_answers: z.array(z.string().max(64)).max(100),
        ai_mode: z.enum([
            'off',
            'manual',
            'auto'
        ]),
        disabled_engines: z.array(z.string().max(64)).max(200),
        units: z.enum(['metric', 'imperial'])
    })
});

/**
 * AI settings retrieved
 */
export const zGetAdminSettingsAiResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('AI settings retrieved'),
    data: z.object({
        enabled: z.boolean(),
        base_url: z.string().max(512),
        model: z.string().max(256),
        system_prompt: z.string().max(8000),
        temperature: z.number().gte(0).lte(2),
        max_tokens: z.int().gte(16).lte(32000),
        context_results: z.int().gte(1).lte(20),
        timeout_ms: z.int().gte(1000).lte(300000),
        extra_headers: z.record(z.string(), z.string()),
        api_key_set: z.boolean(),
        default_system_prompt: z.string()
    })
});

export const zPutAdminSettingsAiBody = z.object({
    enabled: z.boolean().optional(),
    base_url: z.string().max(512).optional(),
    model: z.string().max(256).optional(),
    system_prompt: z.string().max(8000).optional(),
    temperature: z.number().gte(0).lte(2).optional(),
    max_tokens: z.int().gte(16).lte(32000).optional(),
    context_results: z.int().gte(1).lte(20).optional(),
    timeout_ms: z.int().gte(1000).lte(300000).optional(),
    extra_headers: z.record(z.string(), z.string()).optional(),
    api_key: z.string().max(1024).nullish()
});

/**
 * AI settings updated
 */
export const zPutAdminSettingsAiResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('AI settings updated'),
    data: z.object({
        enabled: z.boolean(),
        base_url: z.string().max(512),
        model: z.string().max(256),
        system_prompt: z.string().max(8000),
        temperature: z.number().gte(0).lte(2),
        max_tokens: z.int().gte(16).lte(32000),
        context_results: z.int().gte(1).lte(20),
        timeout_ms: z.int().gte(1000).lte(300000),
        extra_headers: z.record(z.string(), z.string()),
        api_key_set: z.boolean(),
        default_system_prompt: z.string()
    })
});

export const zPostAdminSettingsAiTestBody = z.object({
    enabled: z.boolean().optional(),
    base_url: z.string().max(512).optional(),
    model: z.string().max(256).optional(),
    system_prompt: z.string().max(8000).optional(),
    temperature: z.number().gte(0).lte(2).optional(),
    max_tokens: z.int().gte(16).lte(32000).optional(),
    context_results: z.int().gte(1).lte(20).optional(),
    timeout_ms: z.int().gte(1000).lte(300000).optional(),
    extra_headers: z.record(z.string(), z.string()).optional(),
    api_key: z.string().max(1024).nullish()
});

/**
 * AI endpoint tested
 */
export const zPostAdminSettingsAiTestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('AI endpoint tested'),
    data: z.object({
        ok: z.boolean(),
        latency_ms: z.number(),
        reply: z.string().nullable(),
        error: z.string().nullable()
    })
});

export const zPostAdminSettingsAiModelsBody = z.object({
    enabled: z.boolean().optional(),
    base_url: z.string().max(512).optional(),
    model: z.string().max(256).optional(),
    system_prompt: z.string().max(8000).optional(),
    temperature: z.number().gte(0).lte(2).optional(),
    max_tokens: z.int().gte(16).lte(32000).optional(),
    context_results: z.int().gte(1).lte(20).optional(),
    timeout_ms: z.int().gte(1000).lte(300000).optional(),
    extra_headers: z.record(z.string(), z.string()).optional(),
    api_key: z.string().max(1024).nullish()
});

/**
 * Models retrieved
 */
export const zPostAdminSettingsAiModelsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Models retrieved'),
    data: z.object({
        models: z.array(z.string()),
        error: z.string().nullable()
    })
});

/**
 * Search cache statistics retrieved
 */
export const zGetAdminSettingsCacheResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Search cache statistics retrieved'),
    data: z.object({
        persistent: z.boolean(),
        memory_entries: z.number(),
        disk_entries: z.number(),
        disk_bytes: z.number(),
        in_flight: z.number(),
        hits: z.number(),
        misses: z.number(),
        stale_served: z.number(),
        coalesced: z.number(),
        since: z.number()
    })
});

/**
 * Search cache cleared
 */
export const zPostAdminSettingsCacheClearResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Search cache cleared'),
    data: z.null()
});

/**
 * Dataset status retrieved
 */
export const zGetAdminBangsDatasetResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Dataset status retrieved'),
    data: z.object({
        updated_at: z.number().nullable(),
        count: z.number(),
        last_error: z.string().nullable(),
        source_url: z.string()
    })
});

/**
 * Dataset refreshed
 */
export const zPostAdminBangsDatasetRefreshResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Dataset refreshed'),
    data: z.object({
        updated_at: z.number().nullable(),
        count: z.number(),
        last_error: z.string().nullable(),
        source_url: z.string()
    })
});

/**
 * Bangs retrieved
 */
export const zGetAdminBangsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Bangs retrieved'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        trigger: z.string(),
        name: z.string(),
        url_template: z.string(),
        category: z.string().nullable(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    }))
});

export const zPostAdminBangsBody = z.object({
    trigger: z.string().regex(/^!?[a-z0-9][a-z0-9._+-]{0,31}$/),
    name: z.string().min(1).max(64),
    url_template: z.string().max(2048),
    category: z.string().max(64).nullish().default(null)
});

/**
 * Bang created
 */
export const zPostAdminBangsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Bang created'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        trigger: z.string(),
        name: z.string(),
        url_template: z.string(),
        category: z.string().nullable(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zDeleteAdminBangsByBangIdPath = z.object({
    bangID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Bang deleted
 */
export const zDeleteAdminBangsByBangIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Bang deleted'),
    data: z.null()
});

export const zPutAdminBangsByBangIdBody = z.object({
    trigger: z.string().regex(/^!?[a-z0-9][a-z0-9._+-]{0,31}$/),
    name: z.string().min(1).max(64),
    url_template: z.string().max(2048),
    category: z.string().max(64).nullish().default(null)
});

export const zPutAdminBangsByBangIdPath = z.object({
    bangID: z.int().gt(0).lte(9007199254740991)
});

/**
 * Bang updated
 */
export const zPutAdminBangsByBangIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Bang updated'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        trigger: z.string(),
        name: z.string(),
        url_template: z.string(),
        category: z.string().nullable(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});
